apiVersion: v1
kind: Namespace
metadata:
  name:  ns-posthub--env--
  labels:
    name: ns-posthub--env--


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posthub-mongo
  namespace: ns-posthub--env--
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: posthub-mongo
  template:
    metadata:
      labels:
        app: posthub-mongo
    spec:
      containers:
      - name: posthub-mongo
        image: mongo
        resources:
          requests:
              cpu: "250m"
              memory: "250Mi"
          limits:
            memory: "1500Mi"
            cpu: "2500m"
        ports:
        - containerPort: 27017
          name: posthub-mongo


---
kind: Service
apiVersion: v1
metadata:
  name: posthub-mongo-service
  namespace: ns-posthub--env--
spec:
  selector:
    name: posthub-mongo
  type: ClusterIP
  ports:
  - name: posthub-mongo
    port: 27020
    targetPort: 27017